import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'

/** @type {import('./types').SaveData} */
export default async function saveData(data) {

	/** @type {import('./types').MapReplacer<unknown>} */
	function mapReplacer(_key, value) {
		return value instanceof Map ?
			Array.from(value.entries())
			: value;
	}

	const json = JSON.stringify(data, mapReplacer)
	const out = `
// THIS FILE IS AUTOGENERATED. DO NOT EDIT

// eslint-disable-next-line @stylistic/quotes
const data = ${json}
export default data
	`

	const publicFolder = './public'
	if (!existsSync(publicFolder)) {
		await mkdir(publicFolder)
	}

	const path = `${publicFolder}/data.mjs`
	await writeFile(path, out).catch(console.error)
	console.log(`✅ Saved all data to '${path}'`)
}

